name: Python Application CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode dari repositori
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.10'  # Ganti dengan versi Python yang Anda gunakan

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get install -y libffi-dev libssl-devt

    # Jalankan aplikasi atau pengujian
    - name: Run the application
      run: |
        python main.py
